Update menu.js
romgerman/GTAVMenuVueHtml pull request #8
Opened 2017-10-22 19:31 UTC by rt-2

Added the `DefaultIndex` function I made for myself, quite useful if you want to display let say a scale from -1.0 to 1.0 and have the default value to 0.0
rt-2

2017-10-25 23:34 UTC, romgerman requested changes

2017-10-25 23:34 UTC, romgerman commented on js/menu.js
> +		if (index == -1) index = value.length - 1
Make a check if `value` is an array first. Then better use `index < 0` instead so the index will not fall into negative value.

2017-10-26 21:37 UTC, rt-2 commented on js/menu.js
> +		if (index == -1) index = value.length - 1
https://github.com/romgerman/GTAVMenuVueHtml/pull/8/commits/8616ff03c6983f0ebce648d1374ec2ed1d9d7586

2017-11-21 21:53 UTC, rt-2 commented
I don't see what changes you want me to make sorry.
Is it ok or is there still things you want me to edit.
Thank you,
rt-2

2019-05-07 10:34 UTC, closed without merging